"use client";

import { useState } from "react";
import Link from "next/link";
import { toast } from "sonner";
import { ChevronLeft, Copy, Check } from "lucide-react";

const SCHEMA_SPEC = `You are generating data for OpportunitySignal. Output ONLY a JSON array of opportunity objects (no prose). Each object:

{
  "title": "string (required)",
  "category": "one of: hiring_challenge | hackathon | internship | open_source | other (required)",
  "description": "string — 1-2 sentence summary shown on cards",
  "longDescription": "string — optional, full detail (separate paragraphs with \\n\\n)",
  "organizer": "string — e.g. Amazon, Google, Linux Foundation",
  "companySlug": "string — optional, internal company page slug e.g. amazon",
  "companyUrl": "string — optional, external official URL",
  "eligibility": "string — who can apply",
  "applicationUrl": "string — registration/apply link",
  "logoUrl": "string — optional",
  "opensAt": "ISO date — optional, when registration opens",
  "closesAt": "ISO date — optional, REGISTRATION DEADLINE (the countdown target)",
  "endsAt": "ISO date — optional, final/event end. Item stays 'Ongoing' until this date even after registration closes",
  "eventDate": "ISO date — optional",
  "recurringMonth": "string — optional, e.g. 'February' for yearly programs (LFX, Outreachy)",
  "statusOverride": "optional, force status: '' (auto) | upcoming | registration_open | registration_closed | ongoing | ended",
  "isPPIOffering": true/false,
  "ppiDetails": "string — optional, explain the PPI/fast-track",
  "isDiversity": "true/false — diversity badge",
  "isFemaleOnly": "true/false — women-only badge",
  "isInternational": "true/false — international badge (open globally)",
  "prizes": "string — optional",
  "stipend": "string — optional (for programs/open source)",
  "rounds": [ { "name": "string", "timeline": "string", "description": "string" } ],
  "steps": [ { "step": 1, "title": "string", "description": "string" } ],
  "tips": [ "string" ],
  "timeline": [ { "phase": "string", "period": "string", "description": "string" } ],
  "tags": [ "string" ],
  "featured": "true/false — shows with an animated highlight",
  "published": true
}

Use "rounds" for hiring_challenge/hackathon. Use "steps", "timeline", "tips" for open_source/internship programs. closesAt = registration deadline; endsAt = when the whole thing ends. Set "published": true to make it live immediately.`;

export default function BulkImportPage() {
  const [json, setJson] = useState("");
  const [importing, setImporting] = useState(false);
  const [copied, setCopied] = useState(false);
  const [result, setResult] = useState<{
    inserted: number;
    skipped: number;
    errors: { index: number; title?: string; reason: string }[];
  } | null>(null);

  function copySpec() {
    navigator.clipboard.writeText(SCHEMA_SPEC);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function handleImport() {
    let parsed: unknown;
    try {
      parsed = JSON.parse(json);
    } catch {
      toast.error("Invalid JSON — check your syntax");
      return;
    }

    setImporting(true);
    setResult(null);
    try {
      const res = await fetch("/api/opportunities/bulk", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(parsed),
      });
      const data = await res.json();
      if (res.ok) {
        setResult(data);
        toast.success(`Imported ${data.inserted}, skipped ${data.skipped}`);
      } else {
        toast.error(data.message || "Import failed");
      }
    } catch {
      toast.error("Network error");
    } finally {
      setImporting(false);
    }
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <Link
        href="/admin/opportunities"
        className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors mb-6"
      >
        <ChevronLeft className="w-3.5 h-3.5" />
        Back to opportunities
      </Link>

      <h1 className="text-2xl font-bold mb-2">Bulk Import</h1>
      <p className="text-sm text-muted-foreground mb-6">
        Paste a JSON array of opportunities (e.g. generated by an LLM using the
        spec below), then import them all at once.
      </p>

      {/* LLM spec */}
      <div className="rounded-xl border border-border bg-card mb-6">
        <div className="flex items-center justify-between px-4 py-2.5 border-b border-border">
          <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            LLM Prompt Spec
          </span>
          <button
            onClick={copySpec}
            className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5" /> Copied
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" /> Copy spec
              </>
            )}
          </button>
        </div>
        <pre className="text-[11px] leading-relaxed text-muted-foreground p-4 overflow-x-auto whitespace-pre-wrap max-h-64">
          {SCHEMA_SPEC}
        </pre>
      </div>

      {/* JSON input */}
      <label className="block text-sm font-medium mb-1.5">
        Opportunities JSON
      </label>
      <textarea
        className="w-full px-4 py-3 rounded-xl border border-border bg-background text-xs font-mono min-h-[260px] focus:outline-none focus:ring-2 focus:ring-primary/50"
        value={json}
        onChange={(e) => setJson(e.target.value)}
        placeholder='[ { "title": "Example Hackathon", "category": "hackathon", "description": "...", "published": true } ]'
      />

      <button
        onClick={handleImport}
        disabled={importing || !json.trim()}
        className="mt-4 px-6 py-2.5 rounded-xl text-sm font-semibold bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
      >
        {importing ? "Importing..." : "Validate & Import"}
      </button>

      {/* Result */}
      {result && (
        <div className="mt-6 rounded-xl border border-border bg-card p-4">
          <p className="text-sm font-semibold mb-2">
            Imported {result.inserted} · Skipped {result.skipped}
          </p>
          {result.errors.length > 0 && (
            <ul className="space-y-1 mt-2">
              {result.errors.map((e, i) => (
                <li key={i} className="text-xs text-destructive">
                  Row {e.index + 1}
                  {e.title ? ` (${e.title})` : ""}: {e.reason}
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}
